#!/bin/bash
./target/release/which_ring a-6-deoxy-D-Gulp.pdb/
./target/release/which_ring a-6-deoxy-D-Talp.pdb
./target/release/which_ring a-6-deoxy-D-TalpNAc.pdb
./target/release/which_ring a-6-deoxy-L-Altp.pdb
./target/release/which_ring a-6-deoxy-L-AltpNAc.pdb
./target/release/which_ring a-D-Abep.pdb
./target/release/which_ring a-D-Allp.pdb
./target/release/which_ring a-D-AllpA.pdb
./target/release/which_ring a-D-AllpN.pdb
./target/release/which_ring a-D-AllpNAc.pdb
./target/release/which_ring a-D-Bacp.pdb
./target/release/which_ring a-D-Digp.pdb
./target/release/which_ring a-D-Frup.pdb
./target/release/which_ring a-D-Galp.pdb
./target/release/which_ring a-D-GalpA.pdb
./target/release/which_ring a-D-GalpN.pdb
./target/release/which_ring a-D-GalpNAc.pdb
./target/release/which_ring a-D-Glcp.pdb
./target/release/which_ring a-D-GlcpA.pdb
./target/release/which_ring a-D-GlcpN.pdb
./target/release/which_ring a-D-GlcpNAc.pdb
./target/release/which_ring a-D-Gulp.pdb
./target/release/which_ring a-D-GulpA.pdb
./target/release/which_ring a-D-GulpN.pdb
./target/release/which_ring a-D-GulpNAc.pdb
./target/release/which_ring a-D-Kdnp.pdb
./target/release/which_ring a-D-Kdop.pdb
./target/release/which_ring a-D-Lyxp.pdb
./target/release/which_ring a-D-Manp.pdb
./target/release/which_ring a-D-ManpA.pdb
./target/release/which_ring a-D-ManpN.pdb
./target/release/which_ring a-D-ManpNAc.pdb
./target/release/which_ring a-D-Neup5Ac.pdb
./target/release/which_ring a-D-Neup5Gc.pdb
./target/release/which_ring a-D-Parp.pdb
./target/release/which_ring a-D-Psip.pdb
./target/release/which_ring a-D-Quip.pdb
./target/release/which_ring a-D-Ribp.pdb
./target/release/which_ring a-D-Tagp.pdb
./target/release/which_ring a-D-Talp.pdb
./target/release/which_ring a-D-TalpA.pdb
./target/release/which_ring a-D-TalpN.pdb
./target/release/which_ring a-D-TalpNAc.pdb
./target/release/which_ring a-D-Tyvp.pdb
./target/release/which_ring a-D-Xylp.pdb
./target/release/which_ring a-L-Altp.pdb
./target/release/which_ring a-L-AltpN.pdb
./target/release/which_ring a-L-AltpNAc.pdb
./target/release/which_ring a-L-Arap.pdb
./target/release/which_ring a-L-Colp.pdb
./target/release/which_ring a-L-Fucp.pdb
./target/release/which_ring a-L-FucpNAc.pdb
./target/release/which_ring a-L-Idop.pdb
./target/release/which_ring a-L-IdopA.pdb
./target/release/which_ring a-L-IdopN.pdb
./target/release/which_ring a-L-IdopNAc.pdb
./target/release/which_ring a-L-Rhap.pdb
./target/release/which_ring a-L-RhapNAc.pdb
./target/release/which_ring a-L-Sorp.pdb
./target/release/which_ring a-Neup.pdb
./target/release/which_ring b-6-deoxy-D-Gulp.pdb
./target/release/which_ring b-6-deoxy-D-Talp.pdb
./target/release/which_ring b-6-deoxy-D-TalpNAc.pdb
./target/release/which_ring b-6-deoxy-L-Altp.pdb
./target/release/which_ring b-6-deoxy-L-AltpNAc.pdb
./target/release/which_ring b-D-Abep.pdb
./target/release/which_ring b-D-Allp.pdb
./target/release/which_ring b-D-AllpA.pdb
./target/release/which_ring b-D-AllpN.pdb
./target/release/which_ring b-D-AllpNAc.pdb
./target/release/which_ring b-D-Bacp.pdb
./target/release/which_ring b-D-Digp.pdb
./target/release/which_ring b-D-Frup.pdb
./target/release/which_ring b-D-Galp.pdb
./target/release/which_ring b-D-GalpA.pdb
./target/release/which_ring b-D-GalpN.pdb
./target/release/which_ring b-D-GalpNAc.pdb
./target/release/which_ring b-D-Glcp.pdb
./target/release/which_ring b-D-GlcpA.pdb
./target/release/which_ring b-D-GlcpN.pdb
./target/release/which_ring b-D-GlcpNAc.pdb
./target/release/which_ring b-D-Gulp.pdb
./target/release/which_ring b-D-GulpA.pdb
./target/release/which_ring b-D-GulpN.pdb
./target/release/which_ring b-D-GulpNAc.pdb
./target/release/which_ring b-D-Kdop.pdb
./target/release/which_ring b-D-Lyxp.pdb
./target/release/which_ring b-D-Manp.pdb
./target/release/which_ring b-D-ManpA.pdb
./target/release/which_ring b-D-ManpN.pdb
./target/release/which_ring b-D-ManpNAc.pdb
./target/release/which_ring b-D-Neup5Ac.pdb
./target/release/which_ring b-D-Parp.pdb
./target/release/which_ring b-D-Psip.pdb
./target/release/which_ring b-D-Quip.pdb
./target/release/which_ring b-D-Ribp.pdb
./target/release/which_ring b-D-Tagp.pdb
./target/release/which_ring b-D-Talp.pdb
./target/release/which_ring b-D-TalpA.pdb
./target/release/which_ring b-D-TalpN.pdb
./target/release/which_ring b-D-TalpNAc.pdb
./target/release/which_ring b-D-Tyvp.pdb
./target/release/which_ring b-D-Xylp.pdb
./target/release/which_ring b-L-Altp.pdb
./target/release/which_ring b-L-AltpN.pdb
./target/release/which_ring b-L-AltpNAc.pdb
./target/release/which_ring b-L-Arap.pdb
./target/release/which_ring b-L-Colp.pdb
./target/release/which_ring b-L-Fucp.pdb
./target/release/which_ring b-L-FucpNAc.pdb
./target/release/which_ring b-L-Idop.pdb
./target/release/which_ring b-L-IdopA.pdb
./target/release/which_ring b-L-IdopN.pdb
./target/release/which_ring b-L-IdopNAc.pdb
./target/release/which_ring b-L-Rhap.pdb
./target/release/which_ring b-L-RhapNAc.pdb
./target/release/which_ring "b-L-Sorp.pdb"
